<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="scara_rrrp">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_height" value="0.5"/>
    <xacro:property name="base_radius" value="0.04"/>
    <xacro:property name="link1_length" value="0.3"/>
    <xacro:property name="link2_length" value="0.2"/>
    <xacro:property name="link_width" value="0.05"/>
    <xacro:property name="link_height" value="0.05"/>
    <xacro:property name="joint_housing_radius" value="0.03"/>
    <xacro:property name="joint_housing_height" value="0.12"/>
    <xacro:property name="quill_housing_length" value="0.05"/>
    <xacro:property name="quill_housing_radius" value="0.03"/>
    <xacro:property name="quill_length" value="0.45"/>
    <xacro:property name="quill_radius" value="0.02"/>

    <material name="light_grey">
        <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="blue">
        <color rgba="0.2 0.4 0.8 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.15 0.15 0.15 1.0"/>
    </material>
    <material name="chrome">
        <color rgba="0.85 0.85 0.85 1.0"/>
    </material>

    <link name="world"/>

    <joint name="world_to_base_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
            <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.02"/>
        </inertial>
    </link>

    <joint name="joint1" type="revolute">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-PI}" upper="${PI}" effort="100" velocity="1.0"/>
    </joint>

    <link name="link1">
        <visual>
            <geometry>
                <box size="${link1_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${link1_length/2} 0 ${link_width/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${link1_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${joint_housing_radius}" length="${joint_housing_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <inertial>
            <mass value="1.5"/>
            <origin xyz="${link1_length/2} 0 0" rpy="0 0 0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <joint name="joint2" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="${link1_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-PI*0.9}" upper="${PI*0.9}" effort="100" velocity="1.0"/>
    </joint>

    <link name="link2">
        <visual>
            <geometry>
                <box size="${link2_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="${link2_length/2} 0 ${-link_height/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${link2_length} ${link_width} ${link_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <visual>
            <geometry>
                <cylinder radius="${joint_housing_radius}" length="${joint_housing_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <inertial>
            <mass value="1.0"/>
            <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
    </link>

    <joint name="joint3" type="revolute">
        <parent link="link2"/>
        <child link="quill_housing_link"/>
        <origin xyz="${link2_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-PI}" upper="${PI}" effort="50" velocity="2.0"/>
    </joint>

    <link name="quill_housing_link">
        <visual>
            <geometry>
                <cylinder radius="${quill_housing_radius}" length="${quill_housing_length}"/>
            </geometry>
            <origin xyz="0 0 ${-quill_housing_length/2}" rpy="0 0 0"/>
            <material name="light_grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${quill_housing_radius}" length="${quill_housing_length}"/>
            </geometry>
            <origin xyz="0 0 ${-quill_housing_length/2}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="joint4" type="prismatic">
        <parent link="quill_housing_link"/>
        <child link="tool_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit lower="-5.0" upper="5.0" effort="50" velocity="0.5"/>
    </joint>

    <link name="tool_link">
        <visual>
            <geometry>
                <cylinder radius="${quill_radius}" length="${quill_length}"/>
            </geometry>
            <origin xyz="0 0 ${-quill_length/2}" rpy="0 0 0"/>
            <material name="chrome"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${quill_radius}" length="${quill_length}"/>
            </geometry>
            <origin xyz="0 0 ${-quill_length/2}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>
</robot>
