controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # The joint state broadcaster publishes the state of all joints
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # The joint trajectory controller for the arm
    scara_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Parameters for the arm controller
scara_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
